[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/callback"
  status = 200


[[redirects]]
  from = "/login"
  to = "/.netlify/functions/login"
  status = 200

[functions."process_jobs_cron"]
  # run every 5 minutes (adjust as needed)
  schedule = "*/5 * * * *"


[[redirects]]
  # SPA fallback: serve index for all client-side routes
  from = "/*"
  to = "/index.html"
  status = 200
